#!/bin/bash
# Arguments - URL
raw=$(curl $1)
playlist="http://archive.org"$(echo "$raw" | grep ">VBR<" | cut -d \" -f 2)
name=$(echo "$raw" | grep "itemprop=\"name\"" | cut -d \< -f 2 | cut -d \> -f 2 | tail -1)
name=$(echo "$name" | sed 's#/#-#g')
titles=$(echo "$raw" | grep "\"title\":" | grep "mp3" | cut -d \" -f 4 | cut -d \  -f 2-100)
titles=$(echo "$titles" | sed 's#/#-#g')
readarray -t titles <<<"$titles"
files=$(wget -qO- $playlist)
year=$(echo "$raw" | grep "data-year" | tail -1 | cut -d \" -f 2)
mkdir -p "$name"
echo "$files" | xargs -n 1 -P ${#titles[@]} wget2 --progress=bar --max-threads 8 -P "$name" -c # Turn up --max-threads if you have better internet
# Rename files with EasyTAG (Reccomended)
